source 'http://rubygems.org'

gem 'rails', '3.0.1'
gem 'haml'
gem 'oauth'
gem 'json'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'

group :development, :test, :cucumber do
  gem "ruby-debug19", :require => "ruby-debug"
  gem "autotest"
  gem "email_spec"
  gem "autotest-fsevent"
  gem "autotest-growl"
  gem "rspec-rails", ">= 2.0.0.beta.19"
  gem "cucumber-rails", ">= 0.3.2"
  gem "database_cleaner"
  gem "capybara"
  gem "spork"
  gem "launchy"
  gem "shoulda"
  gem "factory_girl"
  gem "escape_utils"
  gem "fakeweb"
end
